# Generated by Django 4.1 on 2022-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_image_file_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='image',
            table='myapp_image',
        ),
    ]
