# Generated by Django 4.1 on 2022-08-27 21:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
